const productList = [
  {
    name: 'Youtheory Collagen + biotin Enhanced formula 390 tablets',
    subName: '',
    img: 'images/products/vitamins/collagen.png',
    stock: true,
    id: 1,
    class: 'vitamins',
    Brand: 'Youtheory',
    'Consumables Form': 'Tablets',
    'Expiry Date': '11/01/2025',
    'Ships From': 'General Tinio, Nueva Ecija'
  },
  {
    name: 'Bath & Body Works Perfume [ORIGINAL ONHAND]',
    subName: 'Bare Vanilla',
    img: 'images/products/perfumes/bare-vanilla.png',
    stock: false,
    id: 2,
    class: 'perfumes',
    Brand: 'Bath & Body Works',
    Gender: 'Unisex',
    Formulation: 'Spray',
    Volume: '236ml',
    Quantity: 1,
    'Ships From': 'General Tinio, Nueva Ecija'
  },{
    name: 'Bath & Body Works Perfume [ORIGINAL ONHAND]',
    subName: 'Berry Waffle Cone',
    img: 'images/products/perfumes/berry-waffle-cone.png',
    stock: true,
    id: 3,
    class: 'perfumes',
    Brand: 'Bath & Body Works',
    Gender: 'Unisex',
    Formulation: 'Spray',
    Volume: '236ml',
    Quantity: 1,
    'Ships From': 'General Tinio, Nueva Ecija'
  },
  {
    name: 'Bath & Body Works Perfume [ORIGINAL ONHAND]',
    subName: 'Fresh Cut Lilacs',
    img: 'images/products/perfumes/fresh-cut-lilacs.png',
    stock: false,
    id: 4,
    class: 'perfumes',
    Brand: 'Bath & Body Works',
    Gender: 'Unisex',
    Formulation: 'Spray',
    Volume: '236ml',
    Quantity: 1,
    'Ships From': 'General Tinio, Nueva Ecija'
  },{
    name: 'Bath & Body Works Perfume [ORIGINAL ONHAND]',
    subName: 'Midnight Bloom',
    img: 'images/products/perfumes/midnight-bloom.png',
    stock: false,
    id: 5,
    class: 'perfumes',
    Brand: 'Bath & Body Works',
    Gender: 'Unisex',
    Formulation: 'Spray',
    Volume: '236ml',
    Quantity: 1,
    'Ships From': 'General Tinio, Nueva Ecija'
  },{
    name: 'Bath & Body Works Perfume [ORIGINAL ONHAND]',
    subName: 'Pink Chiffon',
    img: 'images/products/perfumes/pink-chiffon.png',
    stock: true,
    id: 6,
    class: 'perfumes',
    Brand: 'Bath & Body Works',
    Gender: 'Unisex',
    Formulation: 'Spray',
    Volume: '236ml',
    Quantity: 1,
    'Ships From': 'General Tinio, Nueva Ecija'
  },
  {
    name: 'Bath & Body Works Perfume [ORIGINAL ONHAND]',
    subName: 'Strawberry and Champagne',
    img: 'images/products/perfumes/straw-and-champagne.png',
    stock: false,
    id: 7,
    class: 'perfumes',
    Brand: 'Bath & Body Works',
    Gender: 'Unisex',
    Formulation: 'Spray',
    Volume: '236ml',
    Quantity: 1,
    'Ships From': 'General Tinio, Nueva Ecija'
  },
  {
    name: 'Bath & Body Works Perfume [ORIGINAL ONHAND]',
    subName: 'Twisted Peppermint',
    img: 'images/products/perfumes/twisted-peppermint.png',
    stock: false,
    id: 8,
    class: 'perfumes',
    Brand: 'Bath & Body Works',
    Gender: 'Unisex',
    Formulation: 'Spray',
    Volume: '236ml',
    Quantity: 1,
    'Ships From': 'General Tinio, Nueva Ecija'
  },
  {
    name: 'Bath & Body Works Perfume [ORIGINAL ONHAND]',
    subName: 'Velvet Petals',
    img: 'images/products/perfumes/velvet-petals.png',
    stock: false,
    id: 9,
    class: 'perfumes',
    Brand: 'Bath & Body Works',
    Gender: 'Unisex',
    Formulation: 'Spray',
    Volume: '236ml',
    Quantity: 1,
    'Ships From': 'General Tinio, Nueva Ecija'
  }
];